export default [
  {
    name: "Comic Style Font",
    imageLocation: "../public/comic-preset-sample.webp",
    videoURL: "https://www.youtube.com/embed/tSCZCpNGRus?si=tPbpphrrfEhUf1wa",
    presetFile: "../public/Comic-font-preset.zip",
    thumbnail: "../public/comic-font-thumbnail.webp",
  },
  {
    name: "Deep Fried",
    imageLocation: "../public/deep-fried-sample.webp",
    videoURL: "https://www.youtube.com/embed/1S5YEHuOV_4?si=WRfj2k3rAvGpXCj4",
    presetFile: "../public/Deep-fried-preset.zip",
    thumbnail: "../public/deep-fried-thumbnail.webp",
  },
  {
    name: "Black Vignette",
    imageLocation: "../public/intense-edge-sample.webp",
    videoURL: "https://www.youtube.com/embed/gIkb_LFTtPI?si=U6g7RWHIixQXX4ZZ",
    presetFile: "../public/Black-vignette-preset.zip",
    thumbnail: "../public/black-vignette-thumbnail.webp",
  },
  {
    name: "Uncanny Face",
    imageLocation: "../public/uncanny-face-sample.webp",
    videoURL: "https://www.youtube.com/embed/qzN1kawMNPo?si=fr55J1RE98_zdzOv",
    presetFile: "../public/Uncanny-face-preset.zip",
    thumbnail: "../public/uncanny-face-thumbnail.webp",
  },
  {
    name: "Wholesome Effect",
    imageLocation: "../public/wholesome-preset-sample.webp",
    videoURL: "https://www.youtube.com/embed/eo7ErxAVgao?si=HBT83bUpzuE0VI-y",
    presetFile: "../public/Wholesome-effect-preset.zip",
    thumbnail: "../public/wholesome-effect-thumbnail.webp",
  },
  {
    name: "Distort Audio",
    imageLocation: "../public/audio-preset.webp",
    videoURL: "https://www.youtube.com/embed/djm2_v0-J_o?si=FWiUIyFyhc4_Iv3x",
    presetFile: "../public/Distort-audio-preset.zip",
    thumbnail: "../public/distort-audio-thumbnail.webp",
  },
  {
    name: "Pop-in Text",
    imageLocation: "../public/pop-in-sample-preset.webp",
    videoURL: "https://www.youtube.com/embed/DrlE2zB1lfM?si=QuLS8298eNbwjPpm",
    presetFile: "../public/Pop-in-font-preset.zip",
    thumbnail: "../public/pop-in-text-thumbnail.webp",
  },
  {
    name: "Smooth Shake",
    imageLocation: "../public/smooth-shake-preset-sample.webp",
    videoURL: "https://www.youtube.com/embed/Jt72b8SivQc?si=qaFeA9dnNHf3E6Rz",
    presetFile: "../public/Smooth-shake-preset.zip",
    thumbnail: "../public/smooth-shake-thumbnail.webp",
  },
];
